name: Actions Workflow

on:
  # schedule:
  #   - cron: "0/5 * * * *"
  #   - cron: "0/6 * * * *"
  push:
    branches:
      - main # the Workflow only wil run by a push on main branch
      - 'feature-**' # the Workflow only wil run by a push on a branch starting w/ feature-
      - '!conveyor' # the Workflow won't run in the branch called "conveyor"
    # branches-ignore: # This is to specify in which branches not to run the workflow
    #   - "main"
    tags: # This works exact as branches, also w/ tags-ignore
      - v1
    paths:
      - "**.java" # Will run anytime you push a Java file
      - "!class.java" # Will work for all .java files except this one.
    # paths-ignore: # Only will when include at least one file outside the src directory
    #   - "src/**"
  pull_request:
    types: [closed, assigned, opened]

jobs:
  
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: |
          pwd
          ls -a
      - name: Perform a checkout
        uses: actions/checkout@v1
      - name: List files after checkout  
        run: |
          pwd
          ls -a
          echo $GITHUB_ACTOR
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Simple JS Action
        id: greet
        #uses: ./actions.yml # Reference to an action
        #uses: actions/hello-world-javascript-action@master  # We can reference branches or version like @v1.1 or even a commit with @as2fgb26
        uses: actions/hello-world-javascript-action@master  # Reference to an action
        with: 
          who-to-greet: Bon Jovi
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"    
