name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    #container: node:13.5.0-alpine3.10
    container:
      image: node:13.5.0-alpine3.10
      #options: this will pass the arguments
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
      - name: Log the step container node version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /bin/echo
          args: Hey there! 
        # Echo the node version of this step container based on this 12.14.1-alpine3.10 image
      - name: Step with docker to echo a string
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: /bin/echo
          args: Hello Docker !
  
  check-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Check mvn version
        run: mvn -v
  
  test-template:
    uses: jmedinab5/conveyor-maven-template/.github/workflows/actions/maven-template.yml@main
    